### PR TITLE
Fix/vpc peering #228

### LINKED ISSUE #228: network-peering module generate error when length of local and peered vpc names exceed 62 chars
[vpc-peering](https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/network-peering) module fails when the length of local and peered vpc names are over 62 chars. It will be great if we allow passing vpc peering name or check if the combined length is over 62 chars then crop the combination and add some random chars at the end of peering name. 

Current Code:

```
locals {
  local_network_name = element(reverse(split("/", var.local_network)), 0)
  peer_network_name  = element(reverse(split("/", var.peer_network)), 0)
}

resource "google_compute_network_peering" "local_network_peering" {
  provider             = google-beta
  name                 = "${var.prefix}-${local.local_network_name}-${local.peer_network_name}"
....
}

resource "google_compute_network_peering" "peer_network_peering" {
  provider             = google-beta
  name                 = "${var.prefix}-${local.peer_network_name}-${local.local_network_name}"
....
}
```

### PR DESCRIPTION
**Pull request by imrannayer**
Fixed #228

### CODE REVIEW

**Review by morgante — CHANGES_REQUESTED** [review]
I'd rather not complicate the interface with custom names, but the substring addition is good.

**Comment by imrannayer** [comment]
I'll remove custom names

**Comment by bharathkkb** [comment]
Tests are failing due to a similar error like https://github.com/terraform-google-modules/terraform-google-network/issues/201

**Review by morgante — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
