### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iamolegga**
As there is a new major version let it be set in the docs

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by morgante — APPROVED** [review]

**Comment by morgante** [comment]
@iamolegga You need to sign the CLA.

@bharathkkb Any idea why our bot didn't catch this?

**Comment by iamolegga** [comment]
@morgante already did. Right after I've seen failed check

**Comment by iamolegga** [comment]
FYI same issue with a major version in [cloud-router](https://github.com/terraform-google-modules/terraform-google-cloud-router#usage)

**Comment by bharathkkb** [comment]
@morgante our bot only runs checks against code contents. The CLA runs as a separate check https://github.com/terraform-google-modules/terraform-google-network/pull/346/checks?check_run_id=4860345588. I have re run this check now.

**Comment by morgante** [comment]
@bharathkkb I meant why the release-please bot didn't update this. It looks like [this code](https://github.com/googleapis/release-please/blob/main/src/updaters/terraform/readme.ts) should have.

**Comment by bharathkkb** [comment]
@morgante oh yes, I noticed it a while back. I haven't had a chance to debug release-please but tracking in b/194500618

**Pull request merged**
