### PR TITLE
fix: align subnet modules

### PR DESCRIPTION
**Pull request by tuunit**
As mentioned in #407 I just aligned the two module definition and READMEs, as there are virtually the same as of now and will only be be kept for potential future beta features and backwards compatibility as requested by you @bharathkkb.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@tuunit
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by tuunit** [comment]
Hi @apeabody @bharathkkb,

is this change fine with you?

**Comment by comment-bot-dev** [comment]
@tuunit
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@tuunit
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @tuunit

**Comment by tuunit** [comment]
> Thanks for the PR @tuunit

Thanks for having me and enduring my annoying pinging 😅

**Pull request merged**
