### PR TITLE
Removed locals and hard-coded subnet names in basic example

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by morgante — CHANGES_REQUESTED** [review]
Please upgrade the names in integration tests to match: https://github.com/terraform-google-modules/terraform-google-network/blob/master/test/integration/simple_project/controls/gcloud.rb#L21

**Comment by morgante** [comment]
@betsy-lichtenberg Please rebase on `master`.

**Comment by betsy-lichtenberg** [comment]
> @betsy-lichtenberg Please rebase on `master`.

Done

**Comment by morgante** [comment]
@betsy-lichtenberg It doesn't look merged.

**Comment by betsy-lichtenberg** [comment]
Done

**Comment by betsy-lichtenberg** [comment]
Done

**Review by morgante — APPROVED** [review]

**Pull request merged**
