### PR TITLE
fix: src_threat_intelligences is missing from the variable object definition.

### PR DESCRIPTION
**Pull request by joaquinza**
src_threat_intelligences is missing from the variable object definition.

### CODE REVIEW

**Comment by imrannayer** [comment]
@joaquinza thx for the PR. CLA needs to be signed first.

Thanks

**Comment by joaquinza** [comment]
> @joaquinza thx for the PR. CLA needs to be signed first.
> 
> Thanks

I tried signing it (and when I click on the links, it looks like signed) But for some reason it does not show like signed in the checks. Also I noticed that the check has not re-triggered since the original trigger.

**Comment by joaquinza** [comment]
I added the readme modified by `make generate_docs` but the lint seems to be waiting on something.

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
