### PR TITLE
Set value null if not set

### PR DESCRIPTION
**Pull request by johnroach**
This resolves issue https://github.com/terraform-google-modules/terraform-google-network/issues/112 where empty string values cause issues for new version of provider.

### CODE REVIEW

**Comment by johnroach** [comment]
I don't have access to see why this is failing. Any insight would be most welcomed.

**Comment by johnroach** [comment]
@aaron-lane could I have access to the test results to fix any issues?

**Comment by aaron-lane** [comment]
@johnroach unfortunately, we're not able to provide external access to the build system at this time, but both failures exist on the upstream release/2.0 branch. @morgante I'll pass this over to you since you're overseeing that branch.

**Comment by johnroach** [comment]
Thank you @aaron-lane . @morgante please do ping me if there is anything I can help with. This issue is causing a little pain for a project I am working on. :)

**Comment by johnroach** [comment]
It looks like these changes have already been merged to release-2.0 I am closing this PR. Thank you @morgante !

**Pull request closed without merging**
