### PR TITLE
chore: Remove redundant subnet tests

### PR DESCRIPTION
**Pull request by morgante**
These are already tested via gcloud.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by morgante** [comment]
@bharathkkb PTAL

**Comment by bharathkkb** [comment]
@morgante looks like we are only checking log config in the gcloud tests?

**Comment by morgante** [comment]
@bharathkkb We're also checking to verify the subnet exists.

**Review by bharathkkb — APPROVED** [review]
Perhaps we can remove just `it { should exist }` or switch to just asserting `private_ip_google_access` and `ip_cidr_range` in the gcloud test

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
