### PR TITLE
Release v2.0

### LINKED ISSUE #70: Updating any subnet in a list causes subsequent subnets to be re-created
## Expected behavior

When a subnet is modfied in source, only one resource is modified in the `plan`/`apply`

##  Actual behavior

When a subnet in the list of `var.subnets` is updated or deleted, it forces recreation of all subsequent subnets in the list.

## Example

If I were to update the `subnet_ip` for `subnet-01` it would force re-creation of `subnet-02` as well.

```
module "vpc" {
    source  = "terraform-google-modules/network/google"
    version = "~> 1.0.0"
  
   ...  
   
    subnets = [
        {
            subnet_name           = "subnet-01"
            subnet_ip             = "10.10.10.0/24"
            subnet_region         = "us-west1"
        },
        {
            subnet_name           = "subnet-02"
            subnet_ip             = "10.10.20.0/24"
            subnet_region         = "us-west1"
            subnet_private_access = "true"
            subnet_flow_logs      = "true"
            description           = "This subnet has a description"
        },
    ]
    ...
}
```

### LINKED ISSUE #77: Create Consolidated output
In #73 the topic of outputs came up - https://github.com/terraform-google-modules/terraform-google-network/pull/73#discussion_r327564790  . A feature add to consolidate the outputs (subnets_names, subnets_ips, subnets_regions, subnets_private_access, subnets_flow_logs, subnets_secondary_ranges) into a map indexed by subnet name was proposed. 

I'm creating this issue to track that conversation and works.  

I propose that a new output be created without removing the old outputs so as not introduce a breaking change to this module

### LINKED ISSUE #100: var.subnets count inconsistent with data.google_compute_subnetwork.created_subnets
# Steps to reproduce
1) `terraform apply`
2) `terraform destroy` or change the number of items in `var.subnets`
3) `terraform apply` again. This time it will fail

# Error
Error will be something like this:
```
Error: Error in function call

  on .terraform/modules/vpc/terraform-google-modules-terraform-google-network-7810346/main.tf line 57, in data "google_compute_subnetwork" "created_subnets":
  57:   region     = element(google_compute_subnetwork.subnetwork.*.region, count.index)
    |----------------
    | count.index is 0
    | google_compute_subnetwork.subnetwork is empty tuple

Call to function "element" failed: cannot use element function with an empty
list.
```
# Related issues
#99 Cannot create VPC with only one subnet

### LINKED ISSUE #103: Network 2.0
For the Network 2.0 version, we'd like to make a few architecture changes.

Specifically:
1. Moving subnet creation into a dedicated `subnets` submodule.
2. Moving route creation (and default route deletion) into a `routes` submodule.
3. Move vpc creation into a dedicated `vpc` submodule.
4. Changing the root module into a composition module which still accepts the same (optional) inputs and passes them through to the submodules.

If you want to do everything in 1 module call, you will continue to be able to do so (through the root module). If you want to split things out, you can invoke the root module to *only* create the VPC then directly invoke submodules yourself for the other features.

This should future-proof the architecture and make issues like #100 simpler to deal with.

### LINKED ISSUE #125: FR: Ability to set Sample Rate of subnet flow logs
Feature Request to set sample rate of subnet flow logs. 
Gcp's default is 50% but we want it to be 100%.

### PR DESCRIPTION
**Pull request by morgante**
Release branch for v2.0. Incorporates:
- Fixes #73
- Fixes #108 

Blocked by:
- [x] Working migration script, potentially blocked by https://github.com/hashicorp/terraform/issues/22375
- [x] Fixes #103
- [x] Fixes #77
- [x] Fixes #70 
- [x] Fixes #100
- [x] Fixes #125
- [x] Passing tests
- [x] Manual testing by two people: @morgante and TBD

### CODE REVIEW

**Comment by morgante** [comment]
@tfhartmann It looks like we might be running into https://github.com/hashicorp/terraform/issues/22375

Any chance you could take a look and see why the migration might be failing?

**Comment by tfhartmann** [comment]
> @tfhartmann It looks like we might be running into [hashicorp/terraform#22375](https://github.com/hashicorp/terraform/issues/22375)
> 
> Any chance you could take a look and see why the migration might be failing?

I haven't been able to recreate the issue you're having. The migrations worked for me, and work against the examples created with test kitchen.

**Comment by tfhartmann** [comment]
@morgante was there any progress on this? I'd love to see this merged in.   I wasn't able to replicate the problem you had with the migration script and would like to help if I can.  If there is something I could do let me know 😄

**Comment by morgante** [comment]
@tfhartmann I've been thinking about this some more and want to do a little more rearchitecting before releasing 2.0 so we can avoid multiple state migrations. #103 explains the details.

**Comment by tfhartmann** [comment]
> @tfhartmann I've been thinking about this some more and want to do a little more rearchitecting before releasing 2.0 so we can avoid multiple state migrations. #103 explains the details.

Can I ask that you reconsider?  It would be much more helpful to me as a user of this module to be able to have significant bug fixes merged in. As a user i'd much rather be able to use this module and perform migrations on major releases as needed. Currently I can't use this module until issues like #70 are addresses, as the module in its current form doesn't allow me to mange subnets in a non-destructive way.  I can run off a fork, or find a new module to use I suppose, but that isn't' really ideal. I'd much prefer to support fewer higher quality modules, and this one already has so much good stuff. It is my strong preference to be able to use it if I can rely on it to safely manage my infrastructure.

**Comment by morgante** [comment]
Definitely understand the desire to have this sooner rather than later.

As a compromise, could you consider giving us a week to get the 2.0 version built? If we haven't gotten it by then we can release as-is.

**Comment by tfhartmann** [comment]
> Definitely understand the desire to have this sooner rather than later.
> 
> As a compromise, could you consider giving us a week to get the 2.0 version built? If we haven't gotten it by then we can release as-is.

Absolutely a week would be no problem, and thank you so much for listening to my concerns. I really appreciate it.   Also, if I can help with the refactor in anyway please let me know!

**Comment by tfhartmann** [comment]
> Definitely understand the desire to have this sooner rather than later.
> 
> As a compromise, could you consider giving us a week to get the 2.0 version built? If we haven't gotten it by then we can release as-is.

*bump*

**Comment by johnroach** [comment]
I have created PR https://github.com/terraform-google-modules/terraform-google-network/pull/113 to resolve an issue in regards to route. Would love :eyes: on it if possible.

**Comment by johnroach** [comment]
Hi @morgante and @tfhartmann , please do ping me if there is any way I can help to get this branch released. I would really like this resolved.

**Comment by tfhartmann** [comment]
> Hi @morgante and @tfhartmann , please do ping me if there is any way I can help to get this branch released. I would really like this resolved.

@morgante  I'll echo what @johnroach said. Please do let me know if there is something I could do. I'd also like to see this resolved.

**Comment by morgante** [comment]
@taylorludwig The migration script isn't working for me. Error:

```
../../../modules/network/helpers/migrate.py
---- Migrating the following modules:
-- module.vpc-nonprod.module.vpc
-- module.vpc-prod.module.vpc
---- Commands to run:
Move "module.vpc-nonprod.module.vpc.google_compute_network.network" to "module.vpc-nonprod.module.vpc.module.vpc.google_compute_network.network"
Successfully moved 1 object(s).
Move "module.vpc-nonprod.module.vpc.google_compute_shared_vpc_host_project.shared_vpc_host[0]" to "module.vpc-nonprod.module.vpc.module.vpc.google_compute_shared_vpc_host_project.shared_vpc_host[0]"

Error: Invalid target address

Cannot move to
module.vpc-nonprod.module.vpc.module.vpc.google_compute_shared_vpc_host_project.shared_vpc_host[0]:
module.vpc-nonprod.module.vpc.module.vpc.google_compute_shared_vpc_host_project.shared_vpc_host
does not exist in the current state.

Traceback (most recent call last):
  File "../../../modules/network/helpers/migrate.py", line 422, in <module>
    main(sys.argv)
  File "../../../modules/network/helpers/migrate.py", line 410, in main
    migrate(state=state, dryrun=args.dryrun)
  File "../../../modules/network/helpers/migrate.py", line 401, in migrate
    subprocess.run(argv, check=True, encoding='utf-8')
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['terraform', 'state', 'mv', 'module.vpc-nonprod.module.vpc.google_compute_shared_vpc_host_project.shared_vpc_host[0]', 'module.vpc-nonprod.module.vpc.module.vpc.google_compute_shared_vpc_host_project.shared_vpc_host[0]']' returned non-zero exit status 1.
```

My config:

**Comment by morgante** [comment]
@tfhartmann Sorry for the long delay on this, but finally released!

**Pull request merged**
