### PR TITLE
fix(TF >= 1.3)!: allow optional vars in firewall rules module

### PR DESCRIPTION
**Pull request by zmaupin**
Many of the vars in the firewall rules module are optional.

Notably, log_config should be optional. Instead, the module requires that you set a value and enable logging to use the resource.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall

### CODE REVIEW

**Comment by apeabody** [comment]
Thanks for the contribution @zmaupin - I believe 'optional()' is GA in TF 1.3?  https://github.com/terraform-google-modules/terraform-google-network/blob/master/modules/firewall-rules/versions.tf#L18

**Comment by zmaupin** [comment]
Ok that makes sense @apeabody . How would you like me to proceed? That does seem like a big jump for the module but also, 0.13 is pretty old.

**Comment by apeabody** [comment]
> Ok that makes sense @apeabody . How would you like me to proceed? That does seem like a big jump for the module but also, 0.13 is pretty old.

Thanks @zmaupin - I just checked and let's bump the sub-module TF requirement to `>= 1.3.0`.  This will already be going into a breaking change.

**Comment by apeabody** [comment]
Thanks @zmaupin! - Can you also please update the docs with `make docker_generate_docs` and commit.

```
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/modules/firewall-rules/README.md /tmp/tmp.rUQOBe5NPJ/generate_docs/workspace/modules/firewall-rules/README.md
44c44
< | rules | List of custom rule definitions (refer to variables file for syntax). | <pre>list(object({<br>    name                    = string<br>    description             = string<br>    direction               = string<br>    priority                = number<br>    ranges                  = list(string)<br>    source_tags             = list(string)<br>    source_service_accounts = list(string)<br>    target_tags             = list(string)<br>    target_service_accounts = list(string)<br>    allow = list(object({<br>      protocol = string<br>      ports    = list(string)<br>    }))<br>    deny = list(object({<br>      protocol = string<br>      ports    = list(string)<br>    }))<br>    log_config = object({<br>      metadata = string<br>    })<br>  }))</pre> | `[]` | no |
---
> | rules | List of custom rule definitions (refer to variables file for syntax). | <pre>list(object({<br>    name                    = string<br>    description             = optional(string)<br>    direction               = optional(string)<br>    priority                = optional(number)<br>    ranges                  = optional(list(string))<br>    source_tags             = optional(list(string))<br>    source_service_accounts = optional(list(string))<br>    target_tags             = optional(list(string))<br>    target_service_accounts = optional(list(string))<br>    allow = optional(list(object({<br>      protocol = string<br>      ports    = optional(list(string))<br>    })))<br>    deny = optional(list(object({<br>      protocol = string<br>      ports    = optional(list(string))<br>    })))<br>    log_config = optional(object({<br>      metadata = string<br>    }))<br>  }))</pre> | `[]` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
```

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @zmaupin!

**Pull request merged**
