### PR TITLE
fix: Prevent recreation of serverless connector

### PR DESCRIPTION
**Pull request by ShankyJS**
Been noticing this issue: https://github.com/hashicorp/terraform-provider-google/issues/11304
When using this beta module; it is possible to add that line to prevent it?

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@ShankyJS
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./modules/vpc-serverless-connector-beta/main.tf:38:    
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/vpc-serverless-connector-beta/main.tf
--- old/modules/vpc-serverless-connector-beta/main.tf
+++ new/modules/vpc-serverless-connector-beta/main.tf
@@ -35,7 +35,7 @@
   min_instances  = lookup(each.value, "min_instances", null)
   max_instances  = lookup(each.value, "max_instances", null)
   max_throughput = lookup(each.value, "max_throughput", null)
-    
+
   # REF: https://github.com/hashicorp/terraform-provider-google/issues/11304
   lifecycle {
     ignore_changes = [
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@ShankyJS
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @ShankyJS 
From the PR you linked it seemed like the issue was resolved. Is this not the case?

**Comment by ShankyJS** [comment]
> Thanks for the PR @ShankyJS From the PR you linked it seemed like the issue was resolved. Is this not the case?

Hey @bharathkkb, so I believe they closed because it was fixed on the API side; however when using this module in the version [v5.0.1](https://registry.terraform.io/modules/terraform-google-modules/network/google/latest/submodules/vpc-serverless-connector-beta)

I still get the issue; the PR aims to fix that issue ignoring the changes to the network field (that it's not required by the module anyway). 

[Line of code that I'm trying to solve](https://github.com/terraform-google-modules/terraform-google-network/blob/v5.1.0/modules/vpc-serverless-connector-beta/main.tf#L26)

**Comment by comment-bot-dev** [comment]
@ShankyJS
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request closed without merging**
