### PR TITLE
Set default value for `next_hop_internet` variable

### LINKED ISSUE #63: next_hop_internet should be able to handle a boolean
The variable `next_hop_internet` should be able to handle a boolean value similar to the variables:
shared_vpc_host
subnet_private_access
subnet_flow_logs

The below config throws an error because `next_hop_internet` requires "true"
```    
routes = [
  {
    name = "egress-internet"
    description = "route through IGW to access internet"
    destination_range = "0.0.0.0/0"
    tags = "egress-inet"
    next_hop_internet = true
  }
]
```

### PR DESCRIPTION
**Pull request by paulpalamarchuk**
* Fix #63
 * Fixed default values for `Subnet Inputs` in README.md

### CODE REVIEW

**Comment by paulpalamarchuk** [comment]
Tests made to ensure bool var is acceptable:
image

**Comment by kopachevsky** [comment]
@paulpalamarchuk have you tested use case from #63 with those changes?

**Comment by paulpalamarchuk** [comment]
@kopachevsky yes, I've tested. On screenshot - result of setting this var to `true` (not `"true"`)

**Comment by skenmy** [comment]
LGTM need CODEOWNERS approval

**Comment by morgante** [comment]
@paulpalamarchuk This breaks tests. Please fix.

**Comment by paulpalamarchuk** [comment]
@morgante 
Rebased from master. All tests passed

**Pull request merged**
