### PR TITLE
fix!: Remove subnets-beta module as all feature are fully available

### PR DESCRIPTION
**Pull request by tuunit**
As the role and purpose flags are fully available in the google terraform provider I removed the module subnets-beta

Provider (Purpose): https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_compute_subnetwork.go#L195

Provider (Role): https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_compute_subnetwork.go#L214

Google GO Api Reference: https://pkg.go.dev/google.golang.org/api@v0.103.0/compute/v1#Subnetwork

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@tuunit
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./codelabs/simple
Success!
 The configuration is valid.
terraform_validate ./examples/basic_auto_mode
Success!
 The configuration is valid.
terraform_validate ./examples/basic_custom_mode
Success!
 The configuration is valid.
terraform_validate ./examples/basic_firewall_rule
Success!
 The configuration is valid.
terraform_validate ./examples/basic_secondary_ranges
Success!
 The configuration is valid.
terraform_validate ./examples/basic_shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/basic_vpc_peering
Success!
 The configuration is valid.
terraform_validate ./examples/delete_default_gateway_routes
Success!
 The configuration is valid.
terraform_validate ./examples/firewall_logging
Success!
 The configuration is valid.
terraform_validate ./examples/ilb_routing
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on main.tf line 59, in module "subnets-backup":
│
 
  59:   
module_depends_on
 = [module.subnets.subnets]
│
 
│
 
An argument named "module_depends_on" is not expected here.
╵
terraform_validate ./examples/multi_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/network_service_tiers
Success!
 The configuration is valid.
terraform_validate ./examples/packet_mirroring
Success!
 The configuration is valid.
terraform_validate ./examples/private_service_connect
Success!
 The configuration is valid.
terraform_validate ./examples/private_service_connect_google_apis
Success!
 The configuration is valid.
terraform_validate ./examples/routes
Success!
 The configuration is valid.
terraform_validate ./examples/secondary_ranges
Success!
 The configuration is valid.
terraform_validate ./examples/simple_project
Success!
 The configuration is valid.
terraform_validate ./examples/simple_project_with_regional_network
Success!
 The configuration is valid.
terraform_validate ./examples/submodule_firewall
Success!
 The configuration is valid.
terraform_validate ./examples/submodule_network_peering
Success!
 The configuration is valid.
terraform_validate ./examples/submodule_svpc_access
Success!
 The configuration is valid.
terraform_validate ./examples/submodule_vpc_serverless_connector
Success!
 The configuration is valid.
terraform_validate ./modules/fabric-net-firewall
Success!
 The configuration is valid.
terraform_validate ./modules/fabric-net-svpc-access
Success!
 The configuration is valid.
terraform_validate ./modules/firewall-rules
Success!
 The configuration is valid.
terraform_validate ./modules/network-peering
Success!
 The configuration is valid.
terraform_validate ./modules/private-service-connect
Success!
 The configuration is valid.
terraform_validate ./modules/routes
Success!
 The configuration is valid.
terraform_validate ./modules/routes-beta
Success!
 The configuration is valid.
terraform_validate ./modules/subnets
Success!
 The configuration is valid.
terraform_validate ./modules/vpc
Success!
 The configuration is valid.
terraform_validate ./modules/vpc-serverless-connector-beta
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/delete_default_gateway_routes
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/ilb_routing
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../../examples/ilb_routing/main.tf line 59, in module "subnets-backup":
│
 
  59:   
module_depends_on
 = [module.subnets.subnets]
│
 
│
 
An argument named "module_depends_on" is not expected here.
╵
terraform_validate ./test/fixtures/multi_vpc
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/secondary_ranges
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_project_with_regional_network
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/submodule_firewall
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@tuunit
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@tuunit
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@tuunit
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by bharathkkb** [comment]
@tuunit Thanks for the PR! Although no other features are available today new features could be added in the future to just the beta resources. For that reason I am leaning towards keeping it for now.

**Comment by tuunit** [comment]
@bharathkkb Sounds fine to me. I will just shortly check if the two modules are aligned. If not I might raise a PR to align the beta with ga module.

**Pull request closed without merging**
