### PR TITLE
fix: Document firewall and subnets properties

### PR DESCRIPTION
**Pull request by yuryninog**
Complete the description of the properties:
firewall_rules
subnets
routes
Reported in this issue: https://github.com/terraform-google-modules/terraform-google-network/issues/379

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@yuryninog
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.1kcqg2cIVe/generate_docs/workspace/README.md
105c105
< | firewall\_rules | List of firewall rules | `any` | `[]` | no |
---
> | firewall\_rules | List of maps that represent the firewall rules to be created. Each firewall rule is represented using a map that should contains this data: name, direction, priority, description, ranges, source\_tags, source\_service\_accounts, target\_tags, target\_service\_accounts, allow, deny, log\_config | `any` | `[]` | no |
113c113
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/subnets/README.md /tmp/tmp.1kcqg2cIVe/generate_docs/workspace/modules/subnets/README.md
68c68
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/subnets-beta/README.md /tmp/tmp.1kcqg2cIVe/generate_docs/workspace/modules/subnets-beta/README.md
75c75
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
Checking for missing newline at end of file
Error: No newline at end of file ./.gitignore
 ```

**Comment by comment-bot-dev** [comment]
@yuryninog
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.v33f8k9AYU/generate_docs/workspace/README.md
105c105
< | firewall\_rules | List of firewall rules | `any` | `[]` | no |
---
> | firewall\_rules | List of maps that represent the firewall rules to be created. Each firewall rule is represented using a map that should contains this data: name, direction, priority, description, ranges, source\_tags, source\_service\_accounts, target\_tags, target\_service\_accounts, allow, deny, log\_config | `any` | `[]` | no |
113c113
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/subnets/README.md /tmp/tmp.v33f8k9AYU/generate_docs/workspace/modules/subnets/README.md
68c68
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/subnets-beta/README.md /tmp/tmp.v33f8k9AYU/generate_docs/workspace/modules/subnets-beta/README.md
75c75
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR
Could you also update docs per https://github.com/terraform-google-modules/terraform-google-network/pull/384#issuecomment-1273926659

**Comment by comment-bot-dev** [comment]
@yuryninog
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.br5FKKBT24/generate_docs/workspace/README.md
105c105
< | firewall\_rules | List of firewall rules | `any` | `[]` | no |
---
> | firewall\_rules | List of maps that represent the firewall rules to be created. Each firewall rule is represented using a map that should contains this data: name, direction, priority, description, ranges, source\_tags, source\_service\_accounts, target\_tags, target\_service\_accounts, allow, deny, log\_config | `any` | `[]` | no |
113c113
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/subnets/README.md /tmp/tmp.br5FKKBT24/generate_docs/workspace/modules/subnets/README.md
68c68
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/subnets-beta/README.md /tmp/tmp.br5FKKBT24/generate_docs/workspace/modules/subnets-beta/README.md
75c75
< | subnets | The list of subnets being created | `list(map(string))` | n/a | yes |
---
> | subnets | The list of subnets being created | `list(map(any))` | n/a | yes |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Pull request closed without merging**
