### PR TITLE
fix!: update minimum TPG version for log_config

### LINKED ISSUE #380: firewall_rules submodule google provider version range likely incorrect
It says it requires `<5.0,>= 2.12` but when trying the example usage with 3.5.0 it fails with the error: `Blocks of type log_config are not expected here`.

I am assuming `log_config` was added to `google_compute_firewall` after 3.5.0 but this module claims compatibility all the way back to 2.12.0.

### PR DESCRIPTION
**Pull request by apeabody**
Fixes #380

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks @apeabody we can bundle this with https://github.com/terraform-google-modules/terraform-google-network/pull/377 for next breaking

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
