### PR TITLE
feat: Add IPv6 ULA support and document subnet ipv6 support

### PR DESCRIPTION
**Pull request by CrackerJackMack**
* Add support for ULA on VPC network
* Add optional ULA prefix for VPC network
* Add documentation for subnet `stack` to enable dual-stack networking
* Add documentation for IPv6 type to enable either `EXTERNAL` v6 addressing or `INTERNAL` when ULA is enabled in the VPC

### CODE REVIEW

**Comment by CrackerJackMack** [comment]
CLA signed.

**Comment by imrannayer** [comment]
@CrackerJackMack can u plz add the changes in [subnets-beta module](https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/subnets-beta)

**Comment by imrannayer** [comment]
@CrackerJackMack lint test is failing

**Comment by CrackerJackMack** [comment]
I already did and those files were included in the commit. I've rebased the branch and see if that fixes it.

**Comment by CrackerJackMack** [comment]
> @CrackerJackMack can u plz add the changes in [subnets-beta module](https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/subnets-beta)

You want me to move them? okay. will do

**Comment by imrannayer** [comment]
@CrackerJackMack Lint test is still failing. Can you plz check?

**Comment by imrannayer** [comment]
@CrackerJackMack lint test is failing. Plz execute the following.
Thanks

```
make generate_docs
```

**Comment by CrackerJackMack** [comment]
> @CrackerJackMack lint test is failing. Plz execute the following. Thanks
> 
> ```
> make generate_docs
> ```

That's what [09c90c0](https://github.com/terraform-google-modules/terraform-google-network/pull/466/commits/09c90c0d891e087f99bb5dc0ad71a06efc8c9be5) was. I dunno how to resolve this issue.

**Comment by CrackerJackMack** [comment]
Reverted commit, rebased, and squashed.  Here is the diff when I run `make generate_docs` but that's exactly what the linter is complaining about. So lets see if _that_ fixes it.

```diff
diff --git a/codelabs/simple/README.md b/codelabs/simple/README.md
index 89903a5..ca91669 100644
--- a/codelabs/simple/README.md
+++ b/codelabs/simple/README.md
@@ -5,7 +5,7 @@ The Terraform configuration in this directory is used for a [simple codelab](htt
 <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
 ## Inputs

-No inputs.
+No input.

 ## Outputs

diff --git a/examples/submodule_svpc_access/README.md b/examples/submodule_svpc_access/README.md
index 9ac00e3..e75ca75 100644
--- a/examples/submodule_svpc_access/README.md
+++ b/examples/submodule_svpc_access/README.md
@@ -23,6 +23,6 @@ Subnet-level access in this example is only granted to the default GCE service a

 ## Outputs

-No outputs.
+No output.

 <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
```

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
