### PR TITLE
feat: add ingress and egress firewall rules to main module

### LINKED ISSUE #484: add ingress and egress firewall rules in root module
### TL;DR

Add `ingress` and `egress` firewall rules in main module

### Terraform Resources

_No response_

### Detailed design

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imrannayer**
fix #484 #470

### CODE REVIEW

**Review by bharathkkb — APPROVED** [review]
Could we also bump main tf version to `>= 1.3.0`. This shouldn't be breaking as it was indirectly needed anyway when we bumped FW module.

**Comment by sanspace** [comment]
This did break complaining about the variable type for something that was already working on 7.2.0. We might wanna bump it to 8.0 after confirming the breaking behavior. @bharathkkb  @imrannayer 

```
Error: Invalid value for input variable
│ 
│   on ../../modules/vpc/[main.tf](http://main.tf/) line 9, in module "network_vpc":
│    9:   firewall_rules = var.firewall_rules
│ 
│ The given value is not suitable for module.vpc[1].module.vpc.module.network_vpc.var.firewall_rules declared at
│ .terraform/modules/vpc.vpc.network_vpc/[variables.tf:73](http://variables.tf:73/),1-26: list of object required.
```

We were passing a local var below for the firewall_rules value:

```hcl
   xxxxx_firewall_rules = {
    allow-icmp = {
      name        = "xxxxx-allow-icmp"
      description = null
      direction   = "INGRESS"
      priority    = null
      ranges = [
        "0.0.0.0/0"
      ]
      source_tags             = null
      source_service_accounts = null
      target_tags             = null
      target_service_accounts = null
      allow = [{
        protocol = "icmp"
      }]
      deny = []
      log_config = {
        metadata = "INCLUDE_ALL_METADATA"
      }
    }
  }
```

**Comment by imrannayer** [comment]
@sanspace can you plz open a separate issue so we can track it?

Thanks

**Pull request merged**
